[build]
rustflags = [
    "-A", "warnings"
]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tarch/riscv64/link.ld",
    "-C", "target-feature=+m,+a,+f,+d,+c",
]

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tarch/aarch64/link.ld",
]
