#!/usr/bin/env python3
"""
Generate Rust kernel type definitions using Azure OpenAI Codex
"""

import os
import sys
import requests
import time

# Azure OpenAI configuration
ENDPOINT = os.environ.get("AZURE_OPENAI_ENDPOINT_1", "")
API_KEY = os.environ.get("AZURE_OPENAI_KEY_1", "")
DEPLOYMENT = os.environ.get("AZURE_OPENAI_DEPLOYMENT_1", "gpt-5.3-codex")
API_VERSION = os.environ.get("AZURE_OPENAI_API_VERSION", "2025-04-01-preview")

def call_codex(prompt: str, max_tokens: int = 2000) -> str:
    """Call Azure OpenAI Codex API"""
    headers = {
        "Content-Type": "application/json",
        "api-key": API_KEY
    }

    payload = {
        "model": DEPLOYMENT,
        "input": prompt,
        "max_tokens": max_tokens
    }

    try:
        response = requests.post(
            f"{ENDPOINT}/openai/responses?api-version={API_VERSION}",
            headers=headers,
            json=payload,
            timeout=120,
            verify=False
        )

        if response.status_code != 200:
            print(f"API Error: {response.status_code}", file=sys.stderr)
            return ""

        result = response.json()
        if result.get("output") and len(result["output"]) > 0:
            content = result["output"][0].get("content", [])
            if content and len(content) > 0:
                return content[0].get("text", "")

        return ""

    except Exception as e:
        print(f"Error calling Codex: {e}", file=sys.stderr)
        return ""

def generate_type_definition(type_name: str) -> str:
    """Generate Rust definition for a kernel type"""

    prompt = f"""You are an expert Rust systems programmer creating Linux kernel FFI bindings.

Generate a complete #[repr(C)] Rust struct definition for the Linux kernel type: `{type_name}`

Requirements:
- Target: Linux kernel 5.10 LTS networking stack
- Use #[repr(C)] for C ABI compatibility
- Include all essential fields from the C struct
- Use correct field types and sizes
- Add minimal doc comment explaining the type
- Use core::ffi types (c_int, c_void, etc.)
- Keep it simple and focused

Output ONLY the Rust code, no explanations."""

    response = call_codex(prompt, max_tokens=1500)

    if "```rust" in response:
        # Extract code from markdown block
        start = response.find("```rust") + 7
        end = response.find("```", start)
        if end > start:
            return response[start:end].strip()

    return response.strip()

# Kernel-specific types that need definitions (exclude stdlib types)
KERNEL_TYPES = [
    # Network headers
    "udphdr", "iphdr", "ipv6hdr", "ethhdr", "ip_esp_hdr",

    # Network addresses
    "in_addr", "in6_addr", "nf_inet_addr",

    # Socket types
    "socklen_t", "udp_sock", "inet_sock", "ipv6_pinfo", "raw6_sock",

    # Network structures
    "dst_entry", "skbuff", "flowi", "rt6_info",

    # Netfilter types
    "nf_conntrack_zone", "nf_conntrack_helper", "nf_conn",

    # IPv6 specific
    "ip6cb", "ip6_frag_state", "ip6_fraglist_iter",

    # Misc kernel types
    "timer_list", "hlist_nulls_node", "xfrm_mode_skb_cb",
    "u64_stats_sync", "rtnl_link_ops", "fib_rule",
    "__be16", "c_size_t"
]

def main():
    print("// Auto-generated Linux kernel type definitions for Rust FFI")
    print("// Generated by scripts/generate_kernel_types.py")
    print("// Target: Linux kernel 5.10 LTS\n")

    print("#![no_std]")
    print("#![allow(non_camel_case_types)]")
    print("#![allow(dead_code)]\n")

    print("// Re-export core FFI types")
    print("pub use core::ffi::{c_int, c_uint, c_char, c_uchar, c_short, c_ushort, c_long, c_ulong, c_void};")
    print("pub type size_t = usize;")
    print("pub type c_size_t = usize;\n")

    for i, type_name in enumerate(KERNEL_TYPES, 1):
        print(f"// Type {i}/{len(KERNEL_TYPES)}: {type_name}", file=sys.stderr)

        definition = generate_type_definition(type_name)

        if definition:
            print(f"\n// {type_name}")
            print(definition)
        else:
            print(f"// ERROR: Failed to generate {type_name}", file=sys.stderr)
            # Provide placeholder
            print(f"\n// {type_name} (placeholder)")
            print(f"#[repr(C)]")
            print(f"pub struct {type_name} {{")
            print(f"    _data: [u8; 0],")
            print(f"}}")

        # Rate limiting
        time.sleep(0.5)

    print("\n// End of generated types")

if __name__ == "__main__":
    if not ENDPOINT or not API_KEY:
        print("Error: Azure OpenAI credentials not set", file=sys.stderr)
        print("Run: source ~/.azure_openai_credentials", file=sys.stderr)
        sys.exit(1)

    main()
