# Auto-generated by AutoevolveAI Autopoietic Self-Evolution
# Timestamp: 2026-09-20 19:19:31


def deduplicate_traces(records: list[dict]) -> list[dict]:
    """Optimized O(N) deduplication using single-pass tuple hashing."""
    seen: set[tuple[int, str]] = set()
    unique: list[dict] = []
    for r in records:
        key = (r["task_id"], r["signature"])
        if key not in seen:
            seen.add(key)
            unique.append(r)
    return unique


# Run identical benchmark harness
import random  # noqa: E402

random.seed(42)
test_records = [
    {"task_id": i % 300, "signature": f"sig_{i % 150}", "energy": float(i)} for i in range(2000)
]
res = deduplicate_traces(test_records)
print(f"OUTPUT_HASH:{len(res)}_{sum(r['energy'] for r in res):.1f}")
