import json
import subprocess
import os

def escape_latex(s: str) -> str:
    if not s:
        return ""
    replacements = [
        ("&", "\\&"),
        ("%", "\\%"),
        ("$", "\\$"),
        ("#", "\\#"),
        ("_", "\\_"),
        ("^", "\\textasciicircum{}"),
        ("~", "\\textasciitilde{}"),
        ("<", "$<$"),
        (">", "$>$"),
        ("π", "$\\pi$"),
        ("α", "$\\alpha$"),
        ("β", "$\\beta$"),
        ("γ", "$\\gamma$"),
        ("δ", "$\\delta$"),
        ("ε", "$\\epsilon$"),
        ("λ", "$\\lambda$"),
        ("μ", "$\\mu$"),
        ("σ", "$\\sigma$"),
        ("ω", "$\\omega$"),
        ("Δ", "$\\Delta$"),
        ("∇", "$\\nabla$"),
        ("≤", "$\\le$"),
        ("≥", "$\\ge$"),
        ("≠", "$\\ne$"),
        ("≈", "$\\approx$"),
        ("→", "$\\to$"),
        ("∞", "$\\infty$"),
        ("ℏ", "$\\hbar$"),
        ("∈", "$\\in$"),
        ("×", "$\\times$"),
    ]
    for orig, rep in replacements:
        s = s.replace(orig, rep)
    return s

def build_tex():
    with open("results/200_unified_eval_report.json", "r") as f:
        data = json.load(f)
        
    records = data.get("per_problem_results", [])
    
    tex = r"""\documentclass[11pt, a4paper]{article}
\usepackage{amsmath, amssymb, geometry, xcolor, hyperref, caption, booktabs}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\UseRawInputEncoding
\geometry{margin=1in}
\hypersetup{colorlinks=true, linkcolor=blue, urlcolor=blue}

\title{\textbf{ANSE 200-Problem Verification Dossier}\\
\large Formal Mathematics, High-Performance Rust \& Complex Python Physics}
\author{Autopoietic Neuro-Symbolic Energy-based System (ANSE)}
\date{\today}

\begin{document}
\maketitle

\begin{abstract}
This dossier contains the full specification, physical justifications, and source code solutions for the 200-Problem Multidisciplinary Benchmark generated by the ANSE framework. 
The suite spans 100 formally verified Lean 4 problems in mathematics and theoretical physics, 50 high-performance Rust numeric computing kernels, and 50 complex computational physics Python kernels.
All solutions are subjected to the Deterministic Physical Sandbox and graded via the autopoietic energy function $E$.
\end{abstract}

\tableofcontents
\newpage

"""
    math_recs = [r for r in records if r["domain_group"] == "math_physics_formal"]
    rust_recs = [r for r in records if r["domain_group"] == "rust_numerical"]
    python_recs = [r for r in records if r["domain_group"] == "python_computational"]
    
    tex += r"\section{Formal Mathematics \& Theoretical Physics (Lean 4)}" + "\n"
    for r in math_recs:
        pid = escape_latex(r["problem_id"])
        title = escape_latex(r["title"])
        status = r["status"]
        energy = r["energy_score"]
        details = r["details"]
        math_eq = details.get("math_equation", "")
        phys_just = escape_latex(details.get("physics_justification", ""))
        chosen = r["chosen_solution"]
        
        tex += f"\\subsection{{{pid}: {title}}}\n"
        tex += f"\\textbf{{Status:}} {escape_latex(status)} \\hfill \\textbf{{Energy Score ($E$):}} {energy:.4f}\\\\\n"
        if math_eq:
            tex += f"\\textbf{{Equation:}}\n\\begin{{equation*}}\n{math_eq}\n\\end{{equation*}}\n"
        if phys_just:
            tex += f"\\textbf{{Physical Justification:}} {phys_just}\\\\\n"
        tex += f"\\textbf{{Lean 4 Verifiable Proof:}}\n\\begin{{verbatim}}\n{chosen}\n\\end{{verbatim}}\n\n"
        
    tex += r"\newpage" + "\n"
    tex += r"\section{High-Performance Numerical Computing (Rust)}" + "\n"
    for r in rust_recs:
        pid = escape_latex(r["problem_id"])
        title = escape_latex(r["title"])
        status = r["status"]
        energy = r["energy_score"]
        chosen = r["chosen_solution"]
        lat = r["latency_ms"]
        ram = r["memory_mb"]
        
        tex += f"\\subsection{{{pid}: {title}}}\n"
        tex += f"\\textbf{{Status:}} {escape_latex(status)} \\hfill \\textbf{{Energy Score ($E$):}} {energy:.4f}\\\\\n"
        tex += f"\\textbf{{Telemetry:}} Latency: {lat:.2f} ms $|$ Peak RAM: {ram:.2f} MB\\\\\n"
        tex += f"\\textbf{{Rust Implementation:}}\n\\begin{{verbatim}}\n{chosen}\n\\end{{verbatim}}\n\n"
        
    tex += r"\newpage" + "\n"
    tex += r"\section{Computational Physics \& Applied Mathematics (Python)}" + "\n"
    for r in python_recs:
        pid = escape_latex(r["problem_id"])
        title = escape_latex(r["title"])
        status = r["status"]
        energy = r["energy_score"]
        chosen = r["chosen_solution"]
        lat = r["latency_ms"]
        ram = r["memory_mb"]
        
        tex += f"\\subsection{{{pid}: {title}}}\n"
        tex += f"\\textbf{{Status:}} {escape_latex(status)} \\hfill \\textbf{{Energy Score ($E$):}} {energy:.4f}\\\\\n"
        tex += f"\\textbf{{Telemetry:}} Latency: {lat:.2f} ms $|$ Peak RAM: {ram:.2f} MB\\\\\n"
        tex += f"\\textbf{{Python Kernel:}}\n\\begin{{verbatim}}\n{chosen}\n\\end{{verbatim}}\n\n"
        
    tex += r"\end{document}" + "\n"
    return tex

def main():
    tex = build_tex()
    tex_path = "results/200_solutions_dossier.tex"
    with open(tex_path, "w") as f:
        f.write(tex)
    
    print("Compiling LaTeX to PDF with pdflatex...")
    try:
        subprocess.run(["pdflatex", "-interaction=nonstopmode", "-output-directory=results", tex_path], check=True, capture_output=True)
        subprocess.run(["pdflatex", "-interaction=nonstopmode", "-output-directory=results", tex_path], check=True, capture_output=True)
        print("Success! PDF generated at results/200_solutions_dossier.pdf")
    except subprocess.CalledProcessError as e:
        print("LaTeX compilation failed!")
        print(e.stdout.decode('utf-8', errors='replace')[-2000:])
        
if __name__ == "__main__":
    main()
