[package]
name = "syscall_table"
version = "0.4.0"
edition = "2021"

[dependencies]
kernel_types = { path = "../kernel_types" }
ebpf_firewall = { path = "../ebpf_firewall" }
immutable_logs = { path = "../immutable_logs" }
ai_detector = { path = "../ai_detector" }
libc = "0.2"

[lib]
crate-type = ["rlib"]
